#!/bin/bash
# Proper header for a Bash script.

# Cleanup, version 2

# Run as root, of course
# Insert code here to print error message and exit if not root.

LOG_DIR=/var/log

# Variables are better than hard-coded values.
cd /var/log
cat /dev/null > messages
cat /dev/null > wtmp

echo "Log files cleaned up."
