#!/bin/bash

# This line is a comment

echo "A comment will follow." # Comment here.
#			     ^ Note whitespace before #

	# A tab precedes this comment.
initial=( `cat "$startfile" | sed -e '/#/d' | tr -d '\n' |\
# Delete lines containing '#' comment character.
	sed -e 's/\./\. /g' -e 's/_/_ /g'`)
# Excerpted from life.sh script

